-- +migrate Up notransaction
INSERT INTO cities (id, province_id, name) VALUES (1, 1, 'Kabupaten Aceh Barat');
INSERT INTO cities (id, province_id, name) VALUES (2, 1, 'Kabupaten Aceh Barat Daya');
INSERT INTO cities (id, province_id, name) VALUES (3, 1, 'Kabupaten Aceh Besar');
INSERT INTO cities (id, province_id, name) VALUES (4, 1, 'Kabupaten Aceh Jaya');
INSERT INTO cities (id, province_id, name) VALUES (5, 1, 'Kabupaten Aceh Selatan');
INSERT INTO cities (id, province_id, name) VALUES (6, 1, 'Kabupaten Aceh Singkil');
INSERT INTO cities (id, province_id, name) VALUES (7, 1, 'Kabupaten Aceh Tamiang');
INSERT INTO cities (id, province_id, name) VALUES (8, 1, 'Kabupaten Aceh Tengah');
INSERT INTO cities (id, province_id, name) VALUES (9, 1, 'Kabupaten Aceh Tenggara');
INSERT INTO cities (id, province_id, name) VALUES (10, 1, 'Kabupaten Aceh Timur');
INSERT INTO cities (id, province_id, name) VALUES (11, 1, 'Kabupaten Aceh Utara');
INSERT INTO cities (id, province_id, name) VALUES (12, 1, 'Kabupaten Bener Meriah');
INSERT INTO cities (id, province_id, name) VALUES (13, 1, 'Kabupaten Bireuen');
INSERT INTO cities (id, province_id, name) VALUES (14, 1, 'Kabupaten Gayo Lues');
INSERT INTO cities (id, province_id, name) VALUES (15, 1, 'Kabupaten Nagan Raya');
INSERT INTO cities (id, province_id, name) VALUES (16, 1, 'Kabupaten Pidie');
INSERT INTO cities (id, province_id, name) VALUES (17, 1, 'Kabupaten Pidie Jaya');
INSERT INTO cities (id, province_id, name) VALUES (18, 1, 'Kabupaten Simeulue');
INSERT INTO cities (id, province_id, name) VALUES (19, 1, 'Kota Banda Aceh');
INSERT INTO cities (id, province_id, name) VALUES (20, 1, 'Kota Langsa');
INSERT INTO cities (id, province_id, name) VALUES (21, 1, 'Kota Lhokseumawe');
INSERT INTO cities (id, province_id, name) VALUES (22, 1, 'Kota Sabang');
INSERT INTO cities (id, province_id, name) VALUES (23, 1, 'Kota Subulussalam');
INSERT INTO cities (id, province_id, name) VALUES (24, 2, 'Kabupaten Asahan');
INSERT INTO cities (id, province_id, name) VALUES (25, 2, 'Kabupaten Batu Bara');
INSERT INTO cities (id, province_id, name) VALUES (26, 2, 'Kabupaten Dairi');
INSERT INTO cities (id, province_id, name) VALUES (27, 2, 'Kabupaten Deli Serdang');
INSERT INTO cities (id, province_id, name) VALUES (28, 2, 'Kabupaten Humbang Hasundutan');
INSERT INTO cities (id, province_id, name) VALUES (29, 2, 'Kabupaten Karo');
INSERT INTO cities (id, province_id, name) VALUES (30, 2, 'Kabupaten Labuhanbatu');
INSERT INTO cities (id, province_id, name) VALUES (31, 2, 'Kabupaten Labuhanbatu Selatan');
INSERT INTO cities (id, province_id, name) VALUES (32, 2, 'Kabupaten Labuhanbatu Utara');
INSERT INTO cities (id, province_id, name) VALUES (33, 2, 'Kabupaten Langkat');
INSERT INTO cities (id, province_id, name) VALUES (34, 2, 'Kabupaten Mandailing Natal');
INSERT INTO cities (id, province_id, name) VALUES (35, 2, 'Kabupaten Nias');
INSERT INTO cities (id, province_id, name) VALUES (36, 2, 'Kabupaten Nias Barat');
INSERT INTO cities (id, province_id, name) VALUES (37, 2, 'Kabupaten Nias Selatan');
INSERT INTO cities (id, province_id, name) VALUES (38, 2, 'Kabupaten Nias Utara');
INSERT INTO cities (id, province_id, name) VALUES (39, 2, 'Kabupaten Padang Lawas');
INSERT INTO cities (id, province_id, name) VALUES (40, 2, 'Kabupaten Padang Lawas Utara');
INSERT INTO cities (id, province_id, name) VALUES (41, 2, 'Kabupaten Pakpak Bharat');
INSERT INTO cities (id, province_id, name) VALUES (42, 2, 'Kabupaten Samosir');
INSERT INTO cities (id, province_id, name) VALUES (43, 2, 'Kabupaten Serdang Bedagai');
INSERT INTO cities (id, province_id, name) VALUES (44, 2, 'Kabupaten Simalungun');
INSERT INTO cities (id, province_id, name) VALUES (45, 2, 'Kabupaten Tapanuli Selatan');
INSERT INTO cities (id, province_id, name) VALUES (46, 2, 'Kabupaten Tapanuli Tengah');
INSERT INTO cities (id, province_id, name) VALUES (47, 2, 'Kabupaten Tapanuli Utara');
INSERT INTO cities (id, province_id, name) VALUES (48, 2, 'Kabupaten Toba Samosir');
INSERT INTO cities (id, province_id, name) VALUES (49, 2, 'Kota Binjai');
INSERT INTO cities (id, province_id, name) VALUES (50, 2, 'Kota Gunungsitoli');
INSERT INTO cities (id, province_id, name) VALUES (51, 2, 'Kota Medan');
INSERT INTO cities (id, province_id, name) VALUES (52, 2, 'Kota Padang Sidempuan');
INSERT INTO cities (id, province_id, name) VALUES (53, 2, 'Kota Pematangsiantar');
INSERT INTO cities (id, province_id, name) VALUES (54, 2, 'Kota Sibolga');
INSERT INTO cities (id, province_id, name) VALUES (55, 2, 'Kota Tanjung Balai');
INSERT INTO cities (id, province_id, name) VALUES (56, 2, 'Kota Tebing Tinggi');
INSERT INTO cities (id, province_id, name) VALUES (57, 3, 'Kabupaten Agam');
INSERT INTO cities (id, province_id, name) VALUES (58, 3, 'Kabupaten Dharmasraya');
INSERT INTO cities (id, province_id, name) VALUES (59, 3, 'Kabupaten Kepulauan Mentawai');
INSERT INTO cities (id, province_id, name) VALUES (60, 3, 'Kabupaten Lima Puluh Kota');
INSERT INTO cities (id, province_id, name) VALUES (61, 3, 'Kabupaten Padang Pariaman');
INSERT INTO cities (id, province_id, name) VALUES (62, 3, 'Kabupaten Pasaman');
INSERT INTO cities (id, province_id, name) VALUES (63, 3, 'Kabupaten Pasaman Barat');
INSERT INTO cities (id, province_id, name) VALUES (64, 3, 'Kabupaten Pesisir Selatan');
INSERT INTO cities (id, province_id, name) VALUES (65, 3, 'Kabupaten Sijunjung (Sawah Lunto Sijunjung)');
INSERT INTO cities (id, province_id, name) VALUES (66, 3, 'Kabupaten Solok');
INSERT INTO cities (id, province_id, name) VALUES (67, 3, 'Kabupaten Solok Selatan');
INSERT INTO cities (id, province_id, name) VALUES (68, 3, 'Kabupaten Tanah Datar');
INSERT INTO cities (id, province_id, name) VALUES (69, 3, 'Kota Bukittinggi');
INSERT INTO cities (id, province_id, name) VALUES (70, 3, 'Kota Padang');
INSERT INTO cities (id, province_id, name) VALUES (71, 3, 'Kota Padang Panjang');
INSERT INTO cities (id, province_id, name) VALUES (72, 3, 'Kota Pariaman');
INSERT INTO cities (id, province_id, name) VALUES (73, 3, 'Kota Payakumbuh');
INSERT INTO cities (id, province_id, name) VALUES (74, 3, 'Kota Sawahlunto');
INSERT INTO cities (id, province_id, name) VALUES (75, 3, 'Kota Solok');
INSERT INTO cities (id, province_id, name) VALUES (76, 4, 'Kabupaten Bengkalis');
INSERT INTO cities (id, province_id, name) VALUES (77, 4, 'Kabupaten Indragiri Hilir');
INSERT INTO cities (id, province_id, name) VALUES (78, 4, 'Kabupaten Indragiri Hulu');
INSERT INTO cities (id, province_id, name) VALUES (79, 4, 'Kabupaten Kampar');
INSERT INTO cities (id, province_id, name) VALUES (80, 4, 'Kabupaten Kepulauan Meranti');
INSERT INTO cities (id, province_id, name) VALUES (81, 4, 'Kabupaten Kuantan Singingi');
INSERT INTO cities (id, province_id, name) VALUES (82, 4, 'Kabupaten Pelalawan');
INSERT INTO cities (id, province_id, name) VALUES (83, 4, 'Kabupaten Rokan Hilir');
INSERT INTO cities (id, province_id, name) VALUES (84, 4, 'Kabupaten Rokan Hulu');
INSERT INTO cities (id, province_id, name) VALUES (85, 4, 'Kabupaten Siak');
INSERT INTO cities (id, province_id, name) VALUES (86, 4, 'Kota Dumai');
INSERT INTO cities (id, province_id, name) VALUES (87, 4, 'Kota Pekanbaru');
INSERT INTO cities (id, province_id, name) VALUES (88, 5, 'Kabupaten Batanghari');
INSERT INTO cities (id, province_id, name) VALUES (89, 5, 'Kabupaten Bungo');
INSERT INTO cities (id, province_id, name) VALUES (90, 5, 'Kabupaten Kerinci');
INSERT INTO cities (id, province_id, name) VALUES (91, 5, 'Kabupaten Merangin');
INSERT INTO cities (id, province_id, name) VALUES (92, 5, 'Kabupaten Muaro Jambi');
INSERT INTO cities (id, province_id, name) VALUES (93, 5, 'Kabupaten Sarolangun');
INSERT INTO cities (id, province_id, name) VALUES (94, 5, 'Kabupaten Tanjung Jabung Barat');
INSERT INTO cities (id, province_id, name) VALUES (95, 5, 'Kabupaten Tanjung Jabung Timur');
INSERT INTO cities (id, province_id, name) VALUES (96, 5, 'Kabupaten Tebo');
INSERT INTO cities (id, province_id, name) VALUES (97, 5, 'Kota Jambi');
INSERT INTO cities (id, province_id, name) VALUES (98, 5, 'Kota Sungai Penuh');
INSERT INTO cities (id, province_id, name) VALUES (99, 6, 'Kabupaten Banyuasin');
INSERT INTO cities (id, province_id, name) VALUES (100, 6, 'Kabupaten Empat Lawang');
INSERT INTO cities (id, province_id, name) VALUES (101, 6, 'Kabupaten Lahat');
INSERT INTO cities (id, province_id, name) VALUES (102, 6, 'Kabupaten Muara Enim');
INSERT INTO cities (id, province_id, name) VALUES (103, 6, 'Kabupaten Musi Banyuasin');
INSERT INTO cities (id, province_id, name) VALUES (104, 6, 'Kabupaten Musi Rawas');
INSERT INTO cities (id, province_id, name) VALUES (105, 6, 'Kabupaten Musi Rawas Utara');
INSERT INTO cities (id, province_id, name) VALUES (106, 6, 'Kabupaten Ogan Ilir');
INSERT INTO cities (id, province_id, name) VALUES (107, 6, 'Kabupaten Ogan Komering Ilir');
INSERT INTO cities (id, province_id, name) VALUES (108, 6, 'Kabupaten Ogan Komering Ulu');
INSERT INTO cities (id, province_id, name) VALUES (109, 6, 'Kabupaten Ogan Komering Ulu Selatan (Oku Selatan)');
INSERT INTO cities (id, province_id, name) VALUES (110, 6, 'Kabupaten Ogan Komering Ulu Timur (Oku Timur)');
INSERT INTO cities (id, province_id, name) VALUES (111, 6, 'Kabupaten Penukal Abab Lematang Ilir');
INSERT INTO cities (id, province_id, name) VALUES (112, 6, 'Kota Lubuk Linggau');
INSERT INTO cities (id, province_id, name) VALUES (113, 6, 'Kota Pagar Alam');
INSERT INTO cities (id, province_id, name) VALUES (114, 6, 'Kota Palembang');
INSERT INTO cities (id, province_id, name) VALUES (115, 6, 'Kota Prabumulih');
INSERT INTO cities (id, province_id, name) VALUES (116, 7, 'Kabupaten Bengkulu Selatan');
INSERT INTO cities (id, province_id, name) VALUES (117, 7, 'Kabupaten Bengkulu Tengah');
INSERT INTO cities (id, province_id, name) VALUES (118, 7, 'Kabupaten Bengkulu Utara');
INSERT INTO cities (id, province_id, name) VALUES (119, 7, 'Kabupaten Kaur');
INSERT INTO cities (id, province_id, name) VALUES (120, 7, 'Kabupaten Kepahiang');
INSERT INTO cities (id, province_id, name) VALUES (121, 7, 'Kabupaten Lebong');
INSERT INTO cities (id, province_id, name) VALUES (122, 7, 'Kabupaten Muko Muko');
INSERT INTO cities (id, province_id, name) VALUES (123, 7, 'Kabupaten Rejang Lebong');
INSERT INTO cities (id, province_id, name) VALUES (124, 7, 'Kabupaten Seluma');
INSERT INTO cities (id, province_id, name) VALUES (125, 7, 'Kota Bengkulu');
INSERT INTO cities (id, province_id, name) VALUES (126, 8, 'Kabupaten Lampung Barat');
INSERT INTO cities (id, province_id, name) VALUES (127, 8, 'Kabupaten Lampung Selatan');
INSERT INTO cities (id, province_id, name) VALUES (128, 8, 'Kabupaten Lampung Tengah');
INSERT INTO cities (id, province_id, name) VALUES (129, 8, 'Kabupaten Lampung Timur');
INSERT INTO cities (id, province_id, name) VALUES (130, 8, 'Kabupaten Lampung Utara');
INSERT INTO cities (id, province_id, name) VALUES (131, 8, 'Kabupaten Mesuji');
INSERT INTO cities (id, province_id, name) VALUES (132, 8, 'Kabupaten Pesawaran');
INSERT INTO cities (id, province_id, name) VALUES (133, 8, 'Kabupaten Pesisir Barat');
INSERT INTO cities (id, province_id, name) VALUES (134, 8, 'Kabupaten Pringsewu');
INSERT INTO cities (id, province_id, name) VALUES (135, 8, 'Kabupaten Tanggamus');
INSERT INTO cities (id, province_id, name) VALUES (136, 8, 'Kabupaten Tulang Bawang');
INSERT INTO cities (id, province_id, name) VALUES (137, 8, 'Kabupaten Tulang Bawang Barat');
INSERT INTO cities (id, province_id, name) VALUES (138, 8, 'Kabupaten Way Kanan');
INSERT INTO cities (id, province_id, name) VALUES (139, 8, 'Kota Bandar Lampung');
INSERT INTO cities (id, province_id, name) VALUES (140, 8, 'Kota Metro');
INSERT INTO cities (id, province_id, name) VALUES (141, 9, 'Kabupaten Bangka');
INSERT INTO cities (id, province_id, name) VALUES (142, 9, 'Kabupaten Bangka Barat');
INSERT INTO cities (id, province_id, name) VALUES (143, 9, 'Kabupaten Bangka Selatan');
INSERT INTO cities (id, province_id, name) VALUES (144, 9, 'Kabupaten Bangka Tengah');
INSERT INTO cities (id, province_id, name) VALUES (145, 9, 'Kabupaten Belitung');
INSERT INTO cities (id, province_id, name) VALUES (146, 9, 'Kabupaten Belitung Timur');
INSERT INTO cities (id, province_id, name) VALUES (147, 9, 'Kota Pangkal Pinang');
INSERT INTO cities (id, province_id, name) VALUES (148, 10, 'Kabupaten Bintan');
INSERT INTO cities (id, province_id, name) VALUES (149, 10, 'Kabupaten Karimun');
INSERT INTO cities (id, province_id, name) VALUES (150, 10, 'Kabupaten Kepulauan Anambas');
INSERT INTO cities (id, province_id, name) VALUES (151, 10, 'Kabupaten Lingga');
INSERT INTO cities (id, province_id, name) VALUES (152, 10, 'Kabupaten Natuna');
INSERT INTO cities (id, province_id, name) VALUES (153, 10, 'Kota Batam');
INSERT INTO cities (id, province_id, name) VALUES (154, 10, 'Kota Tanjung Pinang');
INSERT INTO cities (id, province_id, name) VALUES (155, 11, 'Kabupaten Adm. Kepulauan Seribu');
INSERT INTO cities (id, province_id, name) VALUES (156, 11, 'Kota Adm. Jakarta Barat');
INSERT INTO cities (id, province_id, name) VALUES (157, 11, 'Kota Adm. Jakarta Pusat');
INSERT INTO cities (id, province_id, name) VALUES (158, 11, 'Kota Adm. Jakarta Selatan');
INSERT INTO cities (id, province_id, name) VALUES (159, 11, 'Kota Adm. Jakarta Timur');
INSERT INTO cities (id, province_id, name) VALUES (160, 11, 'Kota Adm. Jakarta Utara');
INSERT INTO cities (id, province_id, name) VALUES (161, 12, 'Kabupaten Bandung');
INSERT INTO cities (id, province_id, name) VALUES (162, 12, 'Kabupaten Bandung Barat');
INSERT INTO cities (id, province_id, name) VALUES (163, 12, 'Kabupaten Bekasi');
INSERT INTO cities (id, province_id, name) VALUES (164, 12, 'Kabupaten Bogor');
INSERT INTO cities (id, province_id, name) VALUES (165, 12, 'Kabupaten Ciamis');
INSERT INTO cities (id, province_id, name) VALUES (166, 12, 'Kabupaten Cianjur');
INSERT INTO cities (id, province_id, name) VALUES (167, 12, 'Kabupaten Cirebon');
INSERT INTO cities (id, province_id, name) VALUES (168, 12, 'Kabupaten Garut');
INSERT INTO cities (id, province_id, name) VALUES (169, 12, 'Kabupaten Indramayu');
INSERT INTO cities (id, province_id, name) VALUES (170, 12, 'Kabupaten Karawang');
INSERT INTO cities (id, province_id, name) VALUES (171, 12, 'Kabupaten Kuningan');
INSERT INTO cities (id, province_id, name) VALUES (172, 12, 'Kabupaten Majalengka');
INSERT INTO cities (id, province_id, name) VALUES (173, 12, 'Kabupaten Pangandaran');
INSERT INTO cities (id, province_id, name) VALUES (174, 12, 'Kabupaten Purwakarta');
INSERT INTO cities (id, province_id, name) VALUES (175, 12, 'Kabupaten Subang');
INSERT INTO cities (id, province_id, name) VALUES (176, 12, 'Kabupaten Sukabumi');
INSERT INTO cities (id, province_id, name) VALUES (177, 12, 'Kabupaten Sumedang');
INSERT INTO cities (id, province_id, name) VALUES (178, 12, 'Kabupaten Tasikmalaya');
INSERT INTO cities (id, province_id, name) VALUES (179, 12, 'Kota Bandung');
INSERT INTO cities (id, province_id, name) VALUES (180, 12, 'Kota Banjar');
INSERT INTO cities (id, province_id, name) VALUES (181, 12, 'Kota Bekasi');
INSERT INTO cities (id, province_id, name) VALUES (182, 12, 'Kota Bogor');
INSERT INTO cities (id, province_id, name) VALUES (183, 12, 'Kota Cimahi');
INSERT INTO cities (id, province_id, name) VALUES (184, 12, 'Kota Cirebon');
INSERT INTO cities (id, province_id, name) VALUES (186, 12, 'Kota Sukabumi');
INSERT INTO cities (id, province_id, name) VALUES (187, 12, 'Kota Tasikmalaya');
INSERT INTO cities (id, province_id, name) VALUES (188, 13, 'Kabupaten Banjarnegara');
INSERT INTO cities (id, province_id, name) VALUES (189, 13, 'Kabupaten Banyumas');
INSERT INTO cities (id, province_id, name) VALUES (190, 13, 'Kabupaten Batang');
INSERT INTO cities (id, province_id, name) VALUES (191, 13, 'Kabupaten Blora');
INSERT INTO cities (id, province_id, name) VALUES (192, 13, 'Kabupaten Boyolali');
INSERT INTO cities (id, province_id, name) VALUES (193, 13, 'Kabupaten Brebes');
INSERT INTO cities (id, province_id, name) VALUES (194, 13, 'Kabupaten Cilacap');
INSERT INTO cities (id, province_id, name) VALUES (195, 13, 'Kabupaten Demak');
INSERT INTO cities (id, province_id, name) VALUES (196, 13, 'Kabupaten Grobogan');
INSERT INTO cities (id, province_id, name) VALUES (197, 13, 'Kabupaten Jepara');
INSERT INTO cities (id, province_id, name) VALUES (198, 13, 'Kabupaten Karanganyar');
INSERT INTO cities (id, province_id, name) VALUES (199, 13, 'Kabupaten Kebumen');
INSERT INTO cities (id, province_id, name) VALUES (200, 13, 'Kabupaten Kendal');
INSERT INTO cities (id, province_id, name) VALUES (201, 13, 'Kabupaten Klaten');
INSERT INTO cities (id, province_id, name) VALUES (202, 13, 'Kabupaten Kudus');
INSERT INTO cities (id, province_id, name) VALUES (203, 13, 'Kabupaten Magelang');
INSERT INTO cities (id, province_id, name) VALUES (204, 13, 'Kabupaten Pati');
INSERT INTO cities (id, province_id, name) VALUES (205, 13, 'Kabupaten Pekalongan');
INSERT INTO cities (id, province_id, name) VALUES (206, 13, 'Kabupaten Pemalang');
INSERT INTO cities (id, province_id, name) VALUES (207, 13, 'Kabupaten Purbalingga');
INSERT INTO cities (id, province_id, name) VALUES (208, 13, 'Kabupaten Purworejo');
INSERT INTO cities (id, province_id, name) VALUES (209, 13, 'Kabupaten Rembang');
INSERT INTO cities (id, province_id, name) VALUES (210, 13, 'Kabupaten Semarang');
INSERT INTO cities (id, province_id, name) VALUES (211, 13, 'Kabupaten Sragen');
INSERT INTO cities (id, province_id, name) VALUES (212, 13, 'Kabupaten Sukoharjo');
INSERT INTO cities (id, province_id, name) VALUES (213, 13, 'Kabupaten Tegal');
INSERT INTO cities (id, province_id, name) VALUES (214, 13, 'Kabupaten Temanggung');
INSERT INTO cities (id, province_id, name) VALUES (215, 13, 'Kabupaten Wonogiri');
INSERT INTO cities (id, province_id, name) VALUES (216, 13, 'Kabupaten Wonosobo');
INSERT INTO cities (id, province_id, name) VALUES (217, 13, 'Kota Magelang');
INSERT INTO cities (id, province_id, name) VALUES (218, 13, 'Kota Pekalongan');
INSERT INTO cities (id, province_id, name) VALUES (219, 13, 'Kota Salatiga');
INSERT INTO cities (id, province_id, name) VALUES (220, 13, 'Kota Semarang');
INSERT INTO cities (id, province_id, name) VALUES (221, 13, 'Kota Surakarta (Solo)');
INSERT INTO cities (id, province_id, name) VALUES (222, 13, 'Kota Tegal');
INSERT INTO cities (id, province_id, name) VALUES (223, 14, 'Kabupaten Bantul');
INSERT INTO cities (id, province_id, name) VALUES (224, 14, 'Kabupaten Gunung Kidul');
INSERT INTO cities (id, province_id, name) VALUES (225, 14, 'Kabupaten Kulon Progo');
INSERT INTO cities (id, province_id, name) VALUES (226, 14, 'Kabupaten Sleman');
INSERT INTO cities (id, province_id, name) VALUES (227, 14, 'Kota Yogyakarta');
INSERT INTO cities (id, province_id, name) VALUES (228, 15, 'Kabupaten Bangkalan');
INSERT INTO cities (id, province_id, name) VALUES (229, 15, 'Kabupaten Banyuwangi');
INSERT INTO cities (id, province_id, name) VALUES (230, 15, 'Kabupaten Blitar');
INSERT INTO cities (id, province_id, name) VALUES (231, 15, 'Kabupaten Bojonegoro');
INSERT INTO cities (id, province_id, name) VALUES (232, 15, 'Kabupaten Bondowoso');
INSERT INTO cities (id, province_id, name) VALUES (233, 15, 'Kabupaten Gresik');
INSERT INTO cities (id, province_id, name) VALUES (234, 15, 'Kabupaten Jember');
INSERT INTO cities (id, province_id, name) VALUES (235, 15, 'Kabupaten Jombang');
INSERT INTO cities (id, province_id, name) VALUES (236, 15, 'Kabupaten Kediri');
INSERT INTO cities (id, province_id, name) VALUES (237, 15, 'Kabupaten Lamongan');
INSERT INTO cities (id, province_id, name) VALUES (238, 15, 'Kabupaten Lumajang');
INSERT INTO cities (id, province_id, name) VALUES (239, 15, 'Kabupaten Madiun');
INSERT INTO cities (id, province_id, name) VALUES (240, 15, 'Kabupaten Magetan');
INSERT INTO cities (id, province_id, name) VALUES (241, 15, 'Kabupaten Malang');
INSERT INTO cities (id, province_id, name) VALUES (242, 15, 'Kabupaten Mojokerto');
INSERT INTO cities (id, province_id, name) VALUES (243, 15, 'Kabupaten Nganjuk');
INSERT INTO cities (id, province_id, name) VALUES (244, 15, 'Kabupaten Ngawi');
INSERT INTO cities (id, province_id, name) VALUES (245, 15, 'Kabupaten Pacitan');
INSERT INTO cities (id, province_id, name) VALUES (246, 15, 'Kabupaten Pamekasan');
INSERT INTO cities (id, province_id, name) VALUES (247, 15, 'Kabupaten Pasuruan');
INSERT INTO cities (id, province_id, name) VALUES (248, 15, 'Kabupaten Ponorogo');
INSERT INTO cities (id, province_id, name) VALUES (249, 15, 'Kabupaten Probolinggo');
INSERT INTO cities (id, province_id, name) VALUES (250, 15, 'Kabupaten Sampang');
INSERT INTO cities (id, province_id, name) VALUES (251, 15, 'Kabupaten Sidoarjo');
INSERT INTO cities (id, province_id, name) VALUES (252, 15, 'Kabupaten Situbondo');
INSERT INTO cities (id, province_id, name) VALUES (253, 15, 'Kabupaten Sumenep');
INSERT INTO cities (id, province_id, name) VALUES (254, 15, 'Kabupaten Trenggalek');
INSERT INTO cities (id, province_id, name) VALUES (255, 15, 'Kabupaten Tuban');
INSERT INTO cities (id, province_id, name) VALUES (256, 15, 'Kabupaten Tulungagung');
INSERT INTO cities (id, province_id, name) VALUES (257, 15, 'Kota Batu');
INSERT INTO cities (id, province_id, name) VALUES (258, 15, 'Kota Blitar');
INSERT INTO cities (id, province_id, name) VALUES (259, 15, 'Kota Kediri');
INSERT INTO cities (id, province_id, name) VALUES (260, 15, 'Kota Madiun');
INSERT INTO cities (id, province_id, name) VALUES (261, 15, 'Kota Malang');
INSERT INTO cities (id, province_id, name) VALUES (262, 15, 'Kota Mojokerto');
INSERT INTO cities (id, province_id, name) VALUES (263, 15, 'Kota Pasuruan');
INSERT INTO cities (id, province_id, name) VALUES (264, 15, 'Kota Probolinggo');
INSERT INTO cities (id, province_id, name) VALUES (265, 15, 'Kota Surabaya');
INSERT INTO cities (id, province_id, name) VALUES (266, 16, 'Kabupaten Lebak');
INSERT INTO cities (id, province_id, name) VALUES (267, 16, 'Kabupaten Pandeglang');
INSERT INTO cities (id, province_id, name) VALUES (268, 16, 'Kabupaten Serang');
INSERT INTO cities (id, province_id, name) VALUES (269, 16, 'Kabupaten Tangerang');
INSERT INTO cities (id, province_id, name) VALUES (270, 16, 'Kota Cilegon');
INSERT INTO cities (id, province_id, name) VALUES (271, 16, 'Kota Serang');
INSERT INTO cities (id, province_id, name) VALUES (272, 16, 'Kota Tangerang');
INSERT INTO cities (id, province_id, name) VALUES (273, 16, 'Kota Tangerang Selatan');
INSERT INTO cities (id, province_id, name) VALUES (274, 17, 'Kabupaten Badung');
INSERT INTO cities (id, province_id, name) VALUES (275, 17, 'Kabupaten Bangli');
INSERT INTO cities (id, province_id, name) VALUES (276, 17, 'Kabupaten Buleleng');
INSERT INTO cities (id, province_id, name) VALUES (277, 17, 'Kabupaten Gianyar');
INSERT INTO cities (id, province_id, name) VALUES (278, 17, 'Kabupaten Jembrana');
INSERT INTO cities (id, province_id, name) VALUES (279, 17, 'Kabupaten Karangasem');
INSERT INTO cities (id, province_id, name) VALUES (280, 17, 'Kabupaten Klungkung');
INSERT INTO cities (id, province_id, name) VALUES (281, 17, 'Kabupaten Tabanan');
INSERT INTO cities (id, province_id, name) VALUES (282, 17, 'Kota Denpasar');
INSERT INTO cities (id, province_id, name) VALUES (283, 18, 'Kabupaten Bima');
INSERT INTO cities (id, province_id, name) VALUES (284, 18, 'Kabupaten Dompu');
INSERT INTO cities (id, province_id, name) VALUES (285, 18, 'Kabupaten Lombok Barat');
INSERT INTO cities (id, province_id, name) VALUES (286, 18, 'Kabupaten Lombok Tengah');
INSERT INTO cities (id, province_id, name) VALUES (287, 18, 'Kabupaten Lombok Timur');
INSERT INTO cities (id, province_id, name) VALUES (288, 18, 'Kabupaten Lombok Utara');
INSERT INTO cities (id, province_id, name) VALUES (289, 18, 'Kabupaten Sumbawa');
INSERT INTO cities (id, province_id, name) VALUES (290, 18, 'Kabupaten Sumbawa Barat');
INSERT INTO cities (id, province_id, name) VALUES (291, 18, 'Kota Bima');
INSERT INTO cities (id, province_id, name) VALUES (292, 18, 'Kota Mataram');
INSERT INTO cities (id, province_id, name) VALUES (293, 19, 'Kabupaten Alor');
INSERT INTO cities (id, province_id, name) VALUES (294, 19, 'Kabupaten Belu');
INSERT INTO cities (id, province_id, name) VALUES (295, 19, 'Kabupaten Ende');
INSERT INTO cities (id, province_id, name) VALUES (296, 19, 'Kabupaten Flores Timur');
INSERT INTO cities (id, province_id, name) VALUES (297, 19, 'Kabupaten Kupang');
INSERT INTO cities (id, province_id, name) VALUES (298, 19, 'Kabupaten Lembata');
INSERT INTO cities (id, province_id, name) VALUES (299, 19, 'Kabupaten Malaka');
INSERT INTO cities (id, province_id, name) VALUES (300, 19, 'Kabupaten Manggarai');
INSERT INTO cities (id, province_id, name) VALUES (301, 19, 'Kabupaten Manggarai Barat');
INSERT INTO cities (id, province_id, name) VALUES (302, 19, 'Kabupaten Manggarai Timur');
INSERT INTO cities (id, province_id, name) VALUES (303, 19, 'Kabupaten Nagekeo');
INSERT INTO cities (id, province_id, name) VALUES (304, 19, 'Kabupaten Ngada');
INSERT INTO cities (id, province_id, name) VALUES (305, 19, 'Kabupaten Rote Ndao');
INSERT INTO cities (id, province_id, name) VALUES (306, 19, 'Kabupaten Sabu Raijua');
INSERT INTO cities (id, province_id, name) VALUES (307, 19, 'Kabupaten Sikka');
INSERT INTO cities (id, province_id, name) VALUES (308, 19, 'Kabupaten Sumba Barat');
INSERT INTO cities (id, province_id, name) VALUES (309, 19, 'Kabupaten Sumba Barat Daya');
INSERT INTO cities (id, province_id, name) VALUES (310, 19, 'Kabupaten Sumba Tengah');
INSERT INTO cities (id, province_id, name) VALUES (311, 19, 'Kabupaten Sumba Timur');
INSERT INTO cities (id, province_id, name) VALUES (312, 19, 'Kabupaten Timor Tengah Selatan');
INSERT INTO cities (id, province_id, name) VALUES (313, 19, 'Kabupaten Timor Tengah Utara');
INSERT INTO cities (id, province_id, name) VALUES (314, 19, 'Kota Kupang');
INSERT INTO cities (id, province_id, name) VALUES (315, 20, 'Kabupaten Bengkayang');
INSERT INTO cities (id, province_id, name) VALUES (316, 20, 'Kabupaten Kapuas Hulu');
INSERT INTO cities (id, province_id, name) VALUES (317, 20, 'Kabupaten Kayong Utara');
INSERT INTO cities (id, province_id, name) VALUES (318, 20, 'Kabupaten Ketapang');
INSERT INTO cities (id, province_id, name) VALUES (319, 20, 'Kabupaten Kubu Raya');
INSERT INTO cities (id, province_id, name) VALUES (320, 20, 'Kabupaten Landak');
INSERT INTO cities (id, province_id, name) VALUES (321, 20, 'Kabupaten Melawi');
INSERT INTO cities (id, province_id, name) VALUES (322, 20, 'Kabupaten Mempawah');
INSERT INTO cities (id, province_id, name) VALUES (323, 20, 'Kabupaten Sambas');
INSERT INTO cities (id, province_id, name) VALUES (324, 20, 'Kabupaten Sanggau');
INSERT INTO cities (id, province_id, name) VALUES (325, 20, 'Kabupaten Sekadau');
INSERT INTO cities (id, province_id, name) VALUES (326, 20, 'Kabupaten Sintang');
INSERT INTO cities (id, province_id, name) VALUES (327, 20, 'Kota Pontianak');
INSERT INTO cities (id, province_id, name) VALUES (328, 20, 'Kota Singkawang');
INSERT INTO cities (id, province_id, name) VALUES (329, 21, 'Kabupaten Barito Selatan');
INSERT INTO cities (id, province_id, name) VALUES (330, 21, 'Kabupaten Barito Timur');
INSERT INTO cities (id, province_id, name) VALUES (331, 21, 'Kabupaten Barito Utara');
INSERT INTO cities (id, province_id, name) VALUES (332, 21, 'Kabupaten Gunung Mas');
INSERT INTO cities (id, province_id, name) VALUES (333, 21, 'Kabupaten Kapuas');
INSERT INTO cities (id, province_id, name) VALUES (334, 21, 'Kabupaten Katingan');
INSERT INTO cities (id, province_id, name) VALUES (335, 21, 'Kabupaten Kotawaringin Barat');
INSERT INTO cities (id, province_id, name) VALUES (336, 21, 'Kabupaten Kotawaringin Timur');
INSERT INTO cities (id, province_id, name) VALUES (337, 21, 'Kabupaten Lamandau');
INSERT INTO cities (id, province_id, name) VALUES (338, 21, 'Kabupaten Murung Raya');
INSERT INTO cities (id, province_id, name) VALUES (339, 21, 'Kabupaten Pulang Pisau');
INSERT INTO cities (id, province_id, name) VALUES (340, 21, 'Kabupaten Seruyan');
INSERT INTO cities (id, province_id, name) VALUES (341, 21, 'Kabupaten Sukamara');
INSERT INTO cities (id, province_id, name) VALUES (342, 21, 'Kota Palangka Raya');
INSERT INTO cities (id, province_id, name) VALUES (343, 22, 'Kabupaten Balangan');
INSERT INTO cities (id, province_id, name) VALUES (344, 22, 'Kabupaten Banjar');
INSERT INTO cities (id, province_id, name) VALUES (345, 22, 'Kabupaten Barito Kuala');
INSERT INTO cities (id, province_id, name) VALUES (346, 22, 'Kabupaten Hulu Sungai Selatan');
INSERT INTO cities (id, province_id, name) VALUES (347, 22, 'Kabupaten Hulu Sungai Tengah');
INSERT INTO cities (id, province_id, name) VALUES (348, 22, 'Kabupaten Hulu Sungai Utara');
INSERT INTO cities (id, province_id, name) VALUES (349, 22, 'Kabupaten Kotabaru');
INSERT INTO cities (id, province_id, name) VALUES (350, 22, 'Kabupaten Tabalong');
INSERT INTO cities (id, province_id, name) VALUES (351, 22, 'Kabupaten Tanah Bumbu');
INSERT INTO cities (id, province_id, name) VALUES (352, 22, 'Kabupaten Tanah Laut');
INSERT INTO cities (id, province_id, name) VALUES (353, 22, 'Kabupaten Tapin');
INSERT INTO cities (id, province_id, name) VALUES (354, 22, 'Kota Banjarbaru');
INSERT INTO cities (id, province_id, name) VALUES (355, 22, 'Kota Banjarmasin');
INSERT INTO cities (id, province_id, name) VALUES (356, 23, 'Kabupaten Berau');
INSERT INTO cities (id, province_id, name) VALUES (357, 23, 'Kabupaten Kutai Barat');
INSERT INTO cities (id, province_id, name) VALUES (358, 23, 'Kabupaten Kutai Kartanegara');
INSERT INTO cities (id, province_id, name) VALUES (359, 23, 'Kabupaten Kutai Timur');
INSERT INTO cities (id, province_id, name) VALUES (360, 23, 'Kabupaten Mahakam Ulu');
INSERT INTO cities (id, province_id, name) VALUES (361, 23, 'Kabupaten Paser');
INSERT INTO cities (id, province_id, name) VALUES (362, 23, 'Kabupaten Penajam Paser Utara');
INSERT INTO cities (id, province_id, name) VALUES (363, 23, 'Kota Balikpapan');
INSERT INTO cities (id, province_id, name) VALUES (364, 23, 'Kota Bontang');
INSERT INTO cities (id, province_id, name) VALUES (365, 23, 'Kota Samarinda');
INSERT INTO cities (id, province_id, name) VALUES (366, 24, 'Kabupaten Bulungan (Bulongan)');
INSERT INTO cities (id, province_id, name) VALUES (367, 24, 'Kabupaten Malinau');
INSERT INTO cities (id, province_id, name) VALUES (368, 24, 'Kabupaten Nunukan');
INSERT INTO cities (id, province_id, name) VALUES (369, 24, 'Kabupaten Tana Tidung');
INSERT INTO cities (id, province_id, name) VALUES (370, 24, 'Kota Tarakan');
INSERT INTO cities (id, province_id, name) VALUES (371, 25, 'Kabupaten Bolaang Mongondow');
INSERT INTO cities (id, province_id, name) VALUES (372, 25, 'Kabupaten Bolaang Mongondow Selatan');
INSERT INTO cities (id, province_id, name) VALUES (373, 25, 'Kabupaten Bolaang Mongondow Timur');
INSERT INTO cities (id, province_id, name) VALUES (374, 25, 'Kabupaten Bolaang Mongondow Utara');
INSERT INTO cities (id, province_id, name) VALUES (375, 25, 'Kabupaten Kepulauan Sangihe');
INSERT INTO cities (id, province_id, name) VALUES (376, 25, 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)');
INSERT INTO cities (id, province_id, name) VALUES (377, 25, 'Kabupaten Kepulauan Talaud');
INSERT INTO cities (id, province_id, name) VALUES (378, 25, 'Kabupaten Minahasa');
INSERT INTO cities (id, province_id, name) VALUES (379, 25, 'Kabupaten Minahasa Selatan');
INSERT INTO cities (id, province_id, name) VALUES (380, 25, 'Kabupaten Minahasa Tenggara');
INSERT INTO cities (id, province_id, name) VALUES (381, 25, 'Kabupaten Minahasa Utara');
INSERT INTO cities (id, province_id, name) VALUES (382, 25, 'Kota Bitung');
INSERT INTO cities (id, province_id, name) VALUES (383, 25, 'Kota Kotamobagu');
INSERT INTO cities (id, province_id, name) VALUES (384, 25, 'Kota Manado');
INSERT INTO cities (id, province_id, name) VALUES (385, 25, 'Kota Tomohon');
INSERT INTO cities (id, province_id, name) VALUES (386, 26, 'Kabupaten Banggai');
INSERT INTO cities (id, province_id, name) VALUES (387, 26, 'Kabupaten Banggai Kepulauan');
INSERT INTO cities (id, province_id, name) VALUES (388, 26, 'Kabupaten Banggai Laut');
INSERT INTO cities (id, province_id, name) VALUES (389, 26, 'Kabupaten Buol');
INSERT INTO cities (id, province_id, name) VALUES (390, 26, 'Kabupaten Donggala');
INSERT INTO cities (id, province_id, name) VALUES (391, 26, 'Kabupaten Morowali');
INSERT INTO cities (id, province_id, name) VALUES (392, 26, 'Kabupaten Morowali Utara');
INSERT INTO cities (id, province_id, name) VALUES (393, 26, 'Kabupaten Parigi Moutong');
INSERT INTO cities (id, province_id, name) VALUES (394, 26, 'Kabupaten Poso');
INSERT INTO cities (id, province_id, name) VALUES (395, 26, 'Kabupaten Sigi');
INSERT INTO cities (id, province_id, name) VALUES (396, 26, 'Kabupaten Tojo Una-Una');
INSERT INTO cities (id, province_id, name) VALUES (397, 26, 'Kabupaten Toli-Toli');
INSERT INTO cities (id, province_id, name) VALUES (398, 26, 'Kota Palu');
INSERT INTO cities (id, province_id, name) VALUES (399, 27, 'Kabupaten Bantaeng');
INSERT INTO cities (id, province_id, name) VALUES (400, 27, 'Kabupaten Barru');
INSERT INTO cities (id, province_id, name) VALUES (401, 27, 'Kabupaten Bone');
INSERT INTO cities (id, province_id, name) VALUES (402, 27, 'Kabupaten Bulukumba');
INSERT INTO cities (id, province_id, name) VALUES (403, 27, 'Kabupaten Enrekang');
INSERT INTO cities (id, province_id, name) VALUES (404, 27, 'Kabupaten Gowa');
INSERT INTO cities (id, province_id, name) VALUES (405, 27, 'Kabupaten Jeneponto');
INSERT INTO cities (id, province_id, name) VALUES (406, 27, 'Kabupaten Selayar (Kepulauan Selayar)');
INSERT INTO cities (id, province_id, name) VALUES (407, 27, 'Kabupaten Luwu');
INSERT INTO cities (id, province_id, name) VALUES (408, 27, 'Kabupaten Luwu Timur');
INSERT INTO cities (id, province_id, name) VALUES (409, 27, 'Kabupaten Luwu Utara');
INSERT INTO cities (id, province_id, name) VALUES (410, 27, 'Kabupaten Maros');
INSERT INTO cities (id, province_id, name) VALUES (411, 27, 'Kabupaten Pangkajene Kepulauan');
INSERT INTO cities (id, province_id, name) VALUES (412, 27, 'Kabupaten Pinrang');
INSERT INTO cities (id, province_id, name) VALUES (413, 27, 'Kabupaten Sidenreng Rappang (Sidrap)');
INSERT INTO cities (id, province_id, name) VALUES (414, 27, 'Kabupaten Sinjai');
INSERT INTO cities (id, province_id, name) VALUES (415, 27, 'Kabupaten Soppeng');
INSERT INTO cities (id, province_id, name) VALUES (416, 27, 'Kabupaten Takalar');
INSERT INTO cities (id, province_id, name) VALUES (417, 27, 'Kabupaten Tana Toraja');
INSERT INTO cities (id, province_id, name) VALUES (418, 27, 'Kabupaten Toraja Utara');
INSERT INTO cities (id, province_id, name) VALUES (419, 27, 'Kabupaten Wajo');
INSERT INTO cities (id, province_id, name) VALUES (420, 27, 'Kota Makassar');
INSERT INTO cities (id, province_id, name) VALUES (421, 27, 'Kota Palopo');
INSERT INTO cities (id, province_id, name) VALUES (422, 27, 'Kota Parepare');
INSERT INTO cities (id, province_id, name) VALUES (423, 28, 'Kabupaten Bombana');
INSERT INTO cities (id, province_id, name) VALUES (424, 28, 'Kabupaten Buton');
INSERT INTO cities (id, province_id, name) VALUES (425, 28, 'Kabupaten Buton Selatan');
INSERT INTO cities (id, province_id, name) VALUES (426, 28, 'Kabupaten Buton Tengah');
INSERT INTO cities (id, province_id, name) VALUES (427, 28, 'Kabupaten Buton Utara');
INSERT INTO cities (id, province_id, name) VALUES (428, 28, 'Kabupaten Kolaka');
INSERT INTO cities (id, province_id, name) VALUES (429, 28, 'Kabupaten Kolaka Timur');
INSERT INTO cities (id, province_id, name) VALUES (430, 28, 'Kabupaten Kolaka Utara');
INSERT INTO cities (id, province_id, name) VALUES (431, 28, 'Kabupaten Konawe');
INSERT INTO cities (id, province_id, name) VALUES (432, 28, 'Kabupaten Konawe Kepulauan');
INSERT INTO cities (id, province_id, name) VALUES (433, 28, 'Kabupaten Konawe Selatan');
INSERT INTO cities (id, province_id, name) VALUES (434, 28, 'Kabupaten Konawe Utara');
INSERT INTO cities (id, province_id, name) VALUES (435, 28, 'Kabupaten Muna');
INSERT INTO cities (id, province_id, name) VALUES (436, 28, 'Kabupaten Muna Barat');
INSERT INTO cities (id, province_id, name) VALUES (437, 28, 'Kabupaten Wakatobi');
INSERT INTO cities (id, province_id, name) VALUES (438, 28, 'Kota Baubau');
INSERT INTO cities (id, province_id, name) VALUES (439, 28, 'Kota Kendari');
INSERT INTO cities (id, province_id, name) VALUES (440, 29, 'Kabupaten Boalemo');
INSERT INTO cities (id, province_id, name) VALUES (441, 29, 'Kabupaten Bone Bolango');
INSERT INTO cities (id, province_id, name) VALUES (442, 29, 'Kabupaten Gorontalo');
INSERT INTO cities (id, province_id, name) VALUES (443, 29, 'Kabupaten Gorontalo Utara');
INSERT INTO cities (id, province_id, name) VALUES (444, 29, 'Kabupaten Pohuwato');
INSERT INTO cities (id, province_id, name) VALUES (445, 29, 'Kota Gorontalo');
INSERT INTO cities (id, province_id, name) VALUES (446, 30, 'Kabupaten Majene');
INSERT INTO cities (id, province_id, name) VALUES (447, 30, 'Kabupaten Mamasa');
INSERT INTO cities (id, province_id, name) VALUES (448, 30, 'Kabupaten Mamuju');
INSERT INTO cities (id, province_id, name) VALUES (449, 30, 'Kabupaten Mamuju Tengah');
INSERT INTO cities (id, province_id, name) VALUES (450, 30, 'Kabupaten Mamuju Utara');
INSERT INTO cities (id, province_id, name) VALUES (451, 30, 'Kabupaten Polewali Mandar');
INSERT INTO cities (id, province_id, name) VALUES (452, 31, 'Kabupaten Buru');
INSERT INTO cities (id, province_id, name) VALUES (453, 31, 'Kabupaten Buru Selatan');
INSERT INTO cities (id, province_id, name) VALUES (454, 31, 'Kabupaten Kepulauan Aru');
INSERT INTO cities (id, province_id, name) VALUES (455, 31, 'Kabupaten Maluku Barat Daya');
INSERT INTO cities (id, province_id, name) VALUES (456, 31, 'Kabupaten Maluku Tengah');
INSERT INTO cities (id, province_id, name) VALUES (457, 31, 'Kabupaten Maluku Tenggara');
INSERT INTO cities (id, province_id, name) VALUES (458, 31, 'Kabupaten Maluku Tenggara Barat');
INSERT INTO cities (id, province_id, name) VALUES (459, 31, 'Kabupaten Seram Bagian Barat');
INSERT INTO cities (id, province_id, name) VALUES (460, 31, 'Kabupaten Seram Bagian Timur');
INSERT INTO cities (id, province_id, name) VALUES (461, 31, 'Kota Ambon');
INSERT INTO cities (id, province_id, name) VALUES (462, 31, 'Kota Tual');
INSERT INTO cities (id, province_id, name) VALUES (463, 32, 'Kabupaten Halmahera Barat');
INSERT INTO cities (id, province_id, name) VALUES (464, 32, 'Kabupaten Halmahera Selatan');
INSERT INTO cities (id, province_id, name) VALUES (465, 32, 'Kabupaten Halmahera Tengah');
INSERT INTO cities (id, province_id, name) VALUES (466, 32, 'Kabupaten Halmahera Timur');
INSERT INTO cities (id, province_id, name) VALUES (467, 32, 'Kabupaten Halmahera Utara');
INSERT INTO cities (id, province_id, name) VALUES (468, 32, 'Kabupaten Kepulauan Sula');
INSERT INTO cities (id, province_id, name) VALUES (469, 32, 'Kabupaten Pulau Morotai');
INSERT INTO cities (id, province_id, name) VALUES (470, 32, 'Kabupaten Pulau Taliabu');
INSERT INTO cities (id, province_id, name) VALUES (471, 32, 'Kota Ternate');
INSERT INTO cities (id, province_id, name) VALUES (472, 32, 'Kota Tidore Kepulauan');
INSERT INTO cities (id, province_id, name) VALUES (473, 33, 'Kabupaten Asmat');
INSERT INTO cities (id, province_id, name) VALUES (474, 33, 'Kabupaten Biak Numfor');
INSERT INTO cities (id, province_id, name) VALUES (475, 33, 'Kabupaten Boven Digoel');
INSERT INTO cities (id, province_id, name) VALUES (476, 33, 'Kabupaten Deiyai (Deliyai)');
INSERT INTO cities (id, province_id, name) VALUES (477, 33, 'Kabupaten Dogiyai');
INSERT INTO cities (id, province_id, name) VALUES (478, 33, 'Kabupaten Intan Jaya');
INSERT INTO cities (id, province_id, name) VALUES (479, 33, 'Kabupaten Jayapura');
INSERT INTO cities (id, province_id, name) VALUES (480, 33, 'Kabupaten Jayawijaya');
INSERT INTO cities (id, province_id, name) VALUES (481, 33, 'Kabupaten Keerom');
INSERT INTO cities (id, province_id, name) VALUES (482, 33, 'Kabupaten Kepulauan Yapen (Yapen Waropen)');
INSERT INTO cities (id, province_id, name) VALUES (483, 33, 'Kabupaten Lanny Jaya');
INSERT INTO cities (id, province_id, name) VALUES (484, 33, 'Kabupaten Mamberamo Raya');
INSERT INTO cities (id, province_id, name) VALUES (485, 33, 'Kabupaten Mamberamo Tengah');
INSERT INTO cities (id, province_id, name) VALUES (486, 33, 'Kabupaten Mappi');
INSERT INTO cities (id, province_id, name) VALUES (487, 33, 'Kabupaten Merauke');
INSERT INTO cities (id, province_id, name) VALUES (488, 33, 'Kabupaten Mimika');
INSERT INTO cities (id, province_id, name) VALUES (489, 33, 'Kabupaten Nabire');
INSERT INTO cities (id, province_id, name) VALUES (490, 33, 'Kabupaten Nduga');
INSERT INTO cities (id, province_id, name) VALUES (491, 33, 'Kabupaten Paniai');
INSERT INTO cities (id, province_id, name) VALUES (492, 33, 'Kabupaten Pegunungan Bintang');
INSERT INTO cities (id, province_id, name) VALUES (493, 33, 'Kabupaten Puncak');
INSERT INTO cities (id, province_id, name) VALUES (494, 33, 'Kabupaten Puncak Jaya');
INSERT INTO cities (id, province_id, name) VALUES (495, 33, 'Kabupaten Sarmi');
INSERT INTO cities (id, province_id, name) VALUES (496, 33, 'Kabupaten Supiori');
INSERT INTO cities (id, province_id, name) VALUES (497, 33, 'Kabupaten Tolikara');
INSERT INTO cities (id, province_id, name) VALUES (498, 33, 'Kabupaten Waropen');
INSERT INTO cities (id, province_id, name) VALUES (499, 33, 'Kabupaten Yahukimo');
INSERT INTO cities (id, province_id, name) VALUES (500, 33, 'Kabupaten Yalimo');
INSERT INTO cities (id, province_id, name) VALUES (501, 33, 'Kota Jayapura');
INSERT INTO cities (id, province_id, name) VALUES (502, 34, 'Kabupaten Fakfak');
INSERT INTO cities (id, province_id, name) VALUES (503, 34, 'Kabupaten Kaimana');
INSERT INTO cities (id, province_id, name) VALUES (504, 34, 'Kabupaten Manokwari');
INSERT INTO cities (id, province_id, name) VALUES (505, 34, 'Kabupaten Manokwari Selatan');
INSERT INTO cities (id, province_id, name) VALUES (506, 34, 'Kabupaten Maybrat');
INSERT INTO cities (id, province_id, name) VALUES (507, 34, 'Kabupaten Pegunungan Arfak');
INSERT INTO cities (id, province_id, name) VALUES (508, 34, 'Kabupaten Raja Ampat');
INSERT INTO cities (id, province_id, name) VALUES (509, 34, 'Kabupaten Sorong');
INSERT INTO cities (id, province_id, name) VALUES (510, 34, 'Kabupaten Sorong Selatan');
INSERT INTO cities (id, province_id, name) VALUES (511, 34, 'Kabupaten Tambrauw');
INSERT INTO cities (id, province_id, name) VALUES (512, 34, 'Kabupaten Teluk Bintuni');
INSERT INTO cities (id, province_id, name) VALUES (513, 34, 'Kabupaten Teluk Wondama');
INSERT INTO cities (id, province_id, name) VALUES (514, 34, 'Kota Sorong');
INSERT INTO cities (id, province_id, name) VALUES (185, 12, 'Kota Depok');


-- +migrate Down